spring:
  application:
    name: oauth2client

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            scope: profile, email, openid
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
        provider:
          google:
            issuer-uri: https://accounts.google.com

# oauth 시큐리티 관련 로그 디버그 모드 설정
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.client.endpoint: DEBUG
    org.springframework.security.oauth2.client.web: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.apache.http: DEBUG
