server:
  port: 8082
spring:
  application:
    name: sso-back-app-2

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            scope: profile, email, openid
            redirect-uri: "http://localhost:${server.port}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
        provider:
          google:
            issuer-uri: https://accounts.google.com

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.client.endpoint: DEBUG
    org.springframework.security.oauth2.client.web: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.apache.http: DEBUG
